default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("DB_USERNAME", "me") %>
  password: <%= ENV.fetch("DB_PASSWORD", "") %>
  host: localhost

development:
  <<: *default
  database: kajishare_development

test:
  <<: *default
  database: kajishare_test

production:
  <<: *default
  database: kajishare_production
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>