# Docker, PostgreSQL database configuration
default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kajishare_development

test:
  <<: *default
  database: kajishare_test

production:
  <<: *default
  database: kajishare_production
  username: <%= ENV["POSTGRES_USER"] || "postgres" %>
  password: <%= ENV["POSTGRES_PASSWORD"] || "password" %>
  host: <%= ENV["POSTGRES_HOST"] || "db" %>